interface CodeLanguage {
    language: string,
    alias : string
}

export const CodeLanguages: CodeLanguage[]= [
    { language: 'Plain Text', alias: '' },
    { language: 'C#', alias: 'cs' },
    { language: 'TypeScript', alias: 'ts' },
    { language: 'Java', alias: 'java' },
    { language: 'C', alias: 'c' },
    { language: 'C++', alias: 'cpp' },
    { language: 'BASIC', alias: 'basic' },
    { language: 'JavaScript', alias: 'js' },
    { language: 'ASP.NET', alias: 'aspnet' },
    { language: 'ReactJS', alias: 'jsx' },
    { language: 'CSS', alias: 'css' },
    { language: 'Docker', alias: 'docker' },
    { language: 'F#', alias: 'fsharp' },
    { language: 'Dart', alias: 'dart' },
    { language: 'Fortran', alias: 'fortran' },
    { language: 'Git', alias: 'git' },
    { language: 'Go', alias: 'go' },
    { language: 'HTML', alias: 'html' },
    { language: 'HTTP', alias: 'http' },
    { language: 'Ini', alias: 'ini' },
    { language: 'JSON', alias: 'json' },
    { language: 'Kotlin', alias: 'kt' },
    { language: 'LaTeX', alias: 'latex' },
    { language: 'Lua', alias: 'lua' },
    { language: 'Markdown', alias: 'md' },
    { language: 'MATLAB', alias: 'matlab' },
    { language: 'MongoDB', alias: 'mongodb' },
    { language: 'nginx', alias: 'nginx' },
    { language: 'OCaml', alias: 'ocaml' },
    { language: 'Pascal', alias: 'pascal' },
    { language: 'PHP', alias: 'php' },
    { language: 'PL/SQL', alias: 'plsql' },
    { language: 'PowerShell', alias: 'powershell' },
    { language: 'Python', alias: 'py' },
    { language: 'Q#', alias: 'qs' },
    { language: 'Razor C#', alias: 'cshtml' },
    { language: 'ReactTS', alias: 'tsx' },
    { language: 'Regex', alias: 'regex' },
    { language: 'Rust', alias: 'rust' },
    { language: 'SCSS', alias: 'scss' },
    { language: 'SQL', alias: 'sql' },
    { language: 'VB.Net', alias: 'vbnet' },
    { language: 'Visual Basic', alias: 'vb' },
    { language: 'Web Assembly', alias: 'wasm' },
    { language: 'YAML', alias: 'yaml' },
    { language: 'ABAP', alias: 'abap' },
    { language: 'Agda', alias: 'agda' },
    { language: 'Arduino', alias: 'arduino' },
    { language: 'Assembly', alias: 'armasm' },
    { language: 'Bash', alias: 'bash' },
    { language: 'BNF', alias: 'bnf' },
    { language: 'Clojure', alias: 'clojure' },
    { language: 'CoffeeScript', alias: 'coffeescript' },
    { language: 'Coq', alias: 'coq' },
    { language: 'Dhall', alias: 'dhall' },
    { language: 'Diff', alias: 'diff' },
    { language: 'EBNF', alias: 'ebnf' },
    { language: 'Elixir', alias: 'elixir' },
    { language: 'Elm', alias: 'elm' },
    { language: 'Erlang', alias: 'erlang' },
    { language: 'Flow', alias: 'flow' },
    { language: 'Gherkin', alias: 'gherkin' },
    { language: 'GLSL', alias: 'glsl' },
    { language: 'GraphQL', alias: 'graphql' },
    { language: 'Groovy', alias: 'groovy' },
    { language: 'Haskell', alias: 'haskell' },
    { language: 'Idris', alias: 'idris' },
    { language: 'Julia', alias: 'julia' },
    { language: 'Less', alias: 'less' },
    { language: 'Lisp', alias: 'lisp' },
    { language: 'LiveScript', alias: 'livescript' },
    { language: 'LLVM IR', alias: 'llvm' },
    { language: 'Makefile', alias: 'makefile' },
    { language: 'Markup', alias: 'markup' },
    { language: 'Mermaid', alias: 'mermaid' },
    { language: 'Nix', alias: 'nix' },
    { language: 'Objective-C', alias: 'ojectivec' },
    { language: 'Perl', alias: 'perl' },
    { language: 'Prolog', alias: 'prolog' },
    { language: 'Protobuf', alias: 'protobuf' },
    { language: 'PureScript', alias: 'purescript' },
    { language: 'R', alias: 'r' },
    { language: 'Racket', alias: 'racket' },
    { language: 'Reason', alias: 'reason' },
    { language: 'Ruby', alias: 'ruby' },
    { language: 'Sass', alias: 'sass' },
    { language: 'Scala', alias: 'scala' },
    { language: 'Scheme', alias: 'scheme' },
    { language: 'Shell', alias: 'shell-session' },
    { language: 'Swift', alias: 'swift' },
    { language: 'TOML', alias: 'toml' },
    { language: 'Verilog', alias: 'verilog' },
    { language: 'VHDL', alias: 'vhdl' },
    { language: 'XML', alias: 'xml-doc' },
]